package com.example.resumebuilder.domain.model
data class ResumeTemplateData(
    val fullName: String,
    val professionalTitle: String,
    val email: String,
    val phoneNumber: String,
    val currentLocation: String,
    val professionalSummary: String,
    val workExperiences: List<WorkExperience>,
    val educations: List<Education>,
    val projects: List<Project>,
    val certifications: List<Certification>,
    val skills: List<SkillMustache>,
    val languages: List<SkillMustache>,
    val interests: List<SkillMustache>,
    val achievements: List<SkillMustache>,
    val hasGithub: Boolean,
    val hasLinkedIn: Boolean,
    val hasPortfolio: Boolean,
    val hasProjects: Boolean,
    val hasCertifications: Boolean,
    val hasAchievements: Boolean,
    val hasLanguages: Boolean,
    val hasInterests: Boolean,
    val linkedInUrl: String,
    val githubUrl: String,
    val portfolioUrl: String,
    val includeReferences: Boolean
)
data class SkillMustache(val value: String)